version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: points
      POSTGRES_USER: student
      POSTGRES_PASSWORD: examen
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata:
